name: Build and Deploy Webpage
on:
  push:
    branches: [ develop ]
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
    # if [[ ${changed_file} == "CHANGELOG.md" ]] || [[ ${changed_file} = screenshots* ]] || [[ ${changed_file} = webpage* ]] || [[ ${changed_file} = ".github/workflows/build-deploy-webpage.yml" ]] ;
    paths:
      - 'CHANGELOG.md'
      - 'screenshots/**'
      - 'webpage/**'
      - '.github/workflows/build-deploy-webpage.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: webpage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn run build
      shell: bash
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        #path: ./webpage
        context: ./webpage
        file: ./webpage/Dockerfile
        tags: pbeke/qownnotes-webpage:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
